/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package city.makeour.ngsi.v2.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QueryRequest
 */
class QueryRequestTest {
    private final QueryRequest model = new QueryRequest();

    /**
     * Model tests for QueryRequest
     */
    @Test
    void testQueryRequest() {
        // TODO: test QueryRequest
    }

    /**
     * Test the property 'entities'
     */
    @Test
    void entitiesTest() {
        // TODO: test entities
    }

    /**
     * Test the property 'attrs'
     */
    @Test
    void attrsTest() {
        // TODO: test attrs
    }

    /**
     * Test the property 'expression'
     */
    @Test
    void expressionTest() {
        // TODO: test expression
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

}
