/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package city.makeour.ngsi.v2.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ReplaceAllEntityAttributesRequest
 */
class ReplaceAllEntityAttributesRequestTest {
    private final ReplaceAllEntityAttributesRequest model = new ReplaceAllEntityAttributesRequest();

    /**
     * Model tests for ReplaceAllEntityAttributesRequest
     */
    @Test
    void testReplaceAllEntityAttributesRequest() {
        // TODO: test ReplaceAllEntityAttributesRequest
    }

    /**
     * Test the property 'temperature'
     */
    @Test
    void temperatureTest() {
        // TODO: test temperature
    }

    /**
     * Test the property 'seatNumber'
     */
    @Test
    void seatNumberTest() {
        // TODO: test seatNumber
    }

}
