/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package city.makeour.ngsi.v2.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RetrieveRegistrationResponse
 */
class RetrieveRegistrationResponseTest {
    private final RetrieveRegistrationResponse model = new RetrieveRegistrationResponse();

    /**
     * Model tests for RetrieveRegistrationResponse
     */
    @Test
    void testRetrieveRegistrationResponse() {
        // TODO: test RetrieveRegistrationResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'dataProvided'
     */
    @Test
    void dataProvidedTest() {
        // TODO: test dataProvided
    }

    /**
     * Test the property 'provider'
     */
    @Test
    void providerTest() {
        // TODO: test provider
    }

    /**
     * Test the property 'expires'
     */
    @Test
    void expiresTest() {
        // TODO: test expires
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'forwardingInformation'
     */
    @Test
    void forwardingInformationTest() {
        // TODO: test forwardingInformation
    }

}
