/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package city.makeour.ngsi.v2.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RetrieveEntityTypeResponse
 */
class RetrieveEntityTypeResponseTest {
    private final RetrieveEntityTypeResponse model = new RetrieveEntityTypeResponse();

    /**
     * Model tests for RetrieveEntityTypeResponse
     */
    @Test
    void testRetrieveEntityTypeResponse() {
        // TODO: test RetrieveEntityTypeResponse
    }

    /**
     * Test the property 'attrs'
     */
    @Test
    void attrsTest() {
        // TODO: test attrs
    }

    /**
     * Test the property 'count'
     */
    @Test
    void countTest() {
        // TODO: test count
    }

}
