/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package city.makeour.ngsi.v2.api;

import city.makeour.ngsi.v2.model.CreateRegistrationRequest;
import city.makeour.ngsi.v2.model.ListRegistrationsResponse;
import city.makeour.ngsi.v2.model.RetrieveRegistrationResponse;
import city.makeour.ngsi.v2.model.UpdateRegistrationRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for RegistrationsApi
 */
@Disabled
public class RegistrationsApiTest {

    private final RegistrationsApi api = new RegistrationsApi();

    
    /**
     * Create Registration
     *
     * Creates a new context provider registration. This is typically used for binding context sources as providers of certain data. The registration is represented by a JSON object as described at the beginning of this section. Response: * Successful operation uses 201 Created * Errors use a non-2xx and (optionally) an error payload. See subsection on \&quot;Error Responses\&quot; for   more details.
     */
    @Test
    public void createRegistrationTest()  {
        String contentType = null;
        CreateRegistrationRequest body = null;
        api.createRegistration(contentType, body);

        // TODO: test validations
    }
    
    /**
     * Delete Registration
     *
     * Cancels a context provider registration. Response: * Successful operation uses 204 No Content * Errors use a non-2xx and (optionally) an error payload. See subsection on \&quot;Error Responses\&quot; for   more details.
     */
    @Test
    public void deleteRegistrationTest()  {
        String registrationId = null;
        api.deleteRegistration(registrationId);

        // TODO: test validations
    }
    
    /**
     * List Registrations
     *
     * Lists all the context provider registrations present in the system.
     */
    @Test
    public void listRegistrationsTest()  {
        Double limit = null;
        Double offset = null;
        String options = null;
        List<ListRegistrationsResponse> response = api.listRegistrations(limit, offset, options);

        // TODO: test validations
    }
    
    /**
     * Retrieve Registration
     *
     * The response is the registration represented by a JSON object as described at the beginning of this section. Response: * Successful operation uses 200 OK * Errors use a non-2xx and (optionally) an error payload. See subsection on \&quot;Error Responses\&quot; for   more details.
     */
    @Test
    public void retrieveRegistrationTest()  {
        String registrationId = null;
        RetrieveRegistrationResponse response = api.retrieveRegistration(registrationId);

        // TODO: test validations
    }
    
    /**
     * Update Registration
     *
     * Only the fields included in the request are updated in the registration. Response: * Successful operation uses 204 No Content * Errors use a non-2xx and (optionally) an error payload. See subsection on \&quot;Error Responses\&quot; for   more details.
     */
    @Test
    public void updateRegistrationTest()  {
        String registrationId = null;
        String contentType = null;
        UpdateRegistrationRequest body = null;
        api.updateRegistration(registrationId, contentType, body);

        // TODO: test validations
    }
    
}