/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package city.makeour.ngsi.v2.api;

import city.makeour.ngsi.v2.model.CreateSubscriptionRequest;
import city.makeour.ngsi.v2.model.ListSubscriptionsResponse;
import city.makeour.ngsi.v2.model.UpdateSubscriptionRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for SubscriptionsApi
 */
@Disabled
public class SubscriptionsApiTest {

    private final SubscriptionsApi api = new SubscriptionsApi();

    
    /**
     * Create Subscription
     *
     * Creates a new subscription. The subscription is represented by a JSON object as described at the beginning of this section. Response: * Successful operation uses 201 Created * Errors use a non-2xx and (optionally) an error payload. See subsection on \&quot;Error Responses\&quot; for   more details.
     */
    @Test
    public void createSubscriptionTest()  {
        String contentType = null;
        CreateSubscriptionRequest body = null;
        api.createSubscription(contentType, body);

        // TODO: test validations
    }
    
    /**
     * Delete subscription
     *
     * Cancels subscription. Response: * Successful operation uses 204 No Content * Errors use a non-2xx and (optionally) an error payload. See subsection on \&quot;Error Responses\&quot; for   more details.
     */
    @Test
    public void deleteSubscriptionTest()  {
        String subscriptionId = null;
        api.deleteSubscription(subscriptionId);

        // TODO: test validations
    }
    
    /**
     * List Subscriptions
     *
     * Returns a list of all the subscriptions present in the system. Response: * Successful operation uses 200 OK * Errors use a non-2xx and (optionally) an error payload. See subsection on \&quot;Error Responses\&quot; for   more details.
     */
    @Test
    public void listSubscriptionsTest()  {
        Double limit = null;
        Double offset = null;
        String options = null;
        List<ListSubscriptionsResponse> response = api.listSubscriptions(limit, offset, options);

        // TODO: test validations
    }
    
    /**
     * Retrieve Subscription
     *
     * The response is the subscription represented by a JSON object as described at the beginning of this section. Response: * Successful operation uses 200 OK * Errors use a non-2xx and (optionally) an error payload. See subsection on \&quot;Error Responses\&quot; for   more details.
     */
    @Test
    public void retrieveSubscriptionTest()  {
        String subscriptionId = null;
        Object response = api.retrieveSubscription(subscriptionId);

        // TODO: test validations
    }
    
    /**
     * Update Subscription
     *
     * Only the fields included in the request are updated in the subscription. Response: * Successful operation uses 204 No Content * Errors use a non-2xx and (optionally) an error payload. See subsection on \&quot;Error Responses\&quot; for   more details.
     */
    @Test
    public void updateSubscriptionTest()  {
        String subscriptionId = null;
        String contentType = null;
        UpdateSubscriptionRequest body = null;
        api.updateSubscription(subscriptionId, contentType, body);

        // TODO: test validations
    }
    
}