/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package city.makeour.ngsi.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ListSubscriptionsResponse
 */
@JsonPropertyOrder({
  ListSubscriptionsResponse.JSON_PROPERTY_ID,
  ListSubscriptionsResponse.JSON_PROPERTY_DESCRIPTION,
  ListSubscriptionsResponse.JSON_PROPERTY_SUBJECT,
  ListSubscriptionsResponse.JSON_PROPERTY_NOTIFICATION,
  ListSubscriptionsResponse.JSON_PROPERTY_EXPIRES,
  ListSubscriptionsResponse.JSON_PROPERTY_STATUS,
  ListSubscriptionsResponse.JSON_PROPERTY_THROTTLING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-27T19:56:40.594359+09:00[Asia/Tokyo]", comments = "Generator version: 7.12.0")
public class ListSubscriptionsResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nonnull
  private String description;

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @jakarta.annotation.Nonnull
  private Object subject;

  public static final String JSON_PROPERTY_NOTIFICATION = "notification";
  @jakarta.annotation.Nonnull
  private Object notification;

  public static final String JSON_PROPERTY_EXPIRES = "expires";
  @jakarta.annotation.Nonnull
  private String expires;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private String status;

  public static final String JSON_PROPERTY_THROTTLING = "throttling";
  @jakarta.annotation.Nonnull
  private Integer throttling;

  public ListSubscriptionsResponse() {
  }

  public ListSubscriptionsResponse id(@jakarta.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * 
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public ListSubscriptionsResponse description(@jakarta.annotation.Nonnull String description) {
    
    this.description = description;
    return this;
  }

  /**
   * 
   * @return description
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(@jakarta.annotation.Nonnull String description) {
    this.description = description;
  }

  public ListSubscriptionsResponse subject(@jakarta.annotation.Nonnull Object subject) {
    
    this.subject = subject;
    return this;
  }

  /**
   * 
   * @return subject
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getSubject() {
    return subject;
  }


  @JsonProperty(JSON_PROPERTY_SUBJECT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubject(@jakarta.annotation.Nonnull Object subject) {
    this.subject = subject;
  }

  public ListSubscriptionsResponse notification(@jakarta.annotation.Nonnull Object notification) {
    
    this.notification = notification;
    return this;
  }

  /**
   * 
   * @return notification
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NOTIFICATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getNotification() {
    return notification;
  }


  @JsonProperty(JSON_PROPERTY_NOTIFICATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNotification(@jakarta.annotation.Nonnull Object notification) {
    this.notification = notification;
  }

  public ListSubscriptionsResponse expires(@jakarta.annotation.Nonnull String expires) {
    
    this.expires = expires;
    return this;
  }

  /**
   * 
   * @return expires
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXPIRES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExpires() {
    return expires;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpires(@jakarta.annotation.Nonnull String expires) {
    this.expires = expires;
  }

  public ListSubscriptionsResponse status(@jakarta.annotation.Nonnull String status) {
    
    this.status = status;
    return this;
  }

  /**
   * 
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull String status) {
    this.status = status;
  }

  public ListSubscriptionsResponse throttling(@jakarta.annotation.Nonnull Integer throttling) {
    
    this.throttling = throttling;
    return this;
  }

  /**
   * 
   * @return throttling
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_THROTTLING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getThrottling() {
    return throttling;
  }


  @JsonProperty(JSON_PROPERTY_THROTTLING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setThrottling(@jakarta.annotation.Nonnull Integer throttling) {
    this.throttling = throttling;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListSubscriptionsResponse listSubscriptionsResponse = (ListSubscriptionsResponse) o;
    return Objects.equals(this.id, listSubscriptionsResponse.id) &&
        Objects.equals(this.description, listSubscriptionsResponse.description) &&
        Objects.equals(this.subject, listSubscriptionsResponse.subject) &&
        Objects.equals(this.notification, listSubscriptionsResponse.notification) &&
        Objects.equals(this.expires, listSubscriptionsResponse.expires) &&
        Objects.equals(this.status, listSubscriptionsResponse.status) &&
        Objects.equals(this.throttling, listSubscriptionsResponse.throttling);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, description, subject, notification, expires, status, throttling);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListSubscriptionsResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    notification: ").append(toIndentedString(notification)).append("\n");
    sb.append("    expires: ").append(toIndentedString(expires)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    throttling: ").append(toIndentedString(throttling)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

