/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package city.makeour.ngsi.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * QueryRequest
 */
@JsonPropertyOrder({
  QueryRequest.JSON_PROPERTY_ENTITIES,
  QueryRequest.JSON_PROPERTY_ATTRS,
  QueryRequest.JSON_PROPERTY_EXPRESSION,
  QueryRequest.JSON_PROPERTY_METADATA
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-27T19:56:40.594359+09:00[Asia/Tokyo]", comments = "Generator version: 7.12.0")
public class QueryRequest {
  public static final String JSON_PROPERTY_ENTITIES = "entities";
  @jakarta.annotation.Nonnull
  private List<Object> entities = new ArrayList<>();

  public static final String JSON_PROPERTY_ATTRS = "attrs";
  @jakarta.annotation.Nonnull
  private List<String> attrs = new ArrayList<>();

  public static final String JSON_PROPERTY_EXPRESSION = "expression";
  @jakarta.annotation.Nonnull
  private Object expression;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @jakarta.annotation.Nonnull
  private List<String> metadata = new ArrayList<>();

  public QueryRequest() {
  }

  public QueryRequest entities(@jakarta.annotation.Nonnull List<Object> entities) {
    
    this.entities = entities;
    return this;
  }

  public QueryRequest addEntitiesItem(Object entitiesItem) {
    if (this.entities == null) {
      this.entities = new ArrayList<>();
    }
    this.entities.add(entitiesItem);
    return this;
  }

  /**
   * 
   * @return entities
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Object> getEntities() {
    return entities;
  }


  @JsonProperty(JSON_PROPERTY_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEntities(@jakarta.annotation.Nonnull List<Object> entities) {
    this.entities = entities;
  }

  public QueryRequest attrs(@jakarta.annotation.Nonnull List<String> attrs) {
    
    this.attrs = attrs;
    return this;
  }

  public QueryRequest addAttrsItem(String attrsItem) {
    if (this.attrs == null) {
      this.attrs = new ArrayList<>();
    }
    this.attrs.add(attrsItem);
    return this;
  }

  /**
   * 
   * @return attrs
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ATTRS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getAttrs() {
    return attrs;
  }


  @JsonProperty(JSON_PROPERTY_ATTRS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAttrs(@jakarta.annotation.Nonnull List<String> attrs) {
    this.attrs = attrs;
  }

  public QueryRequest expression(@jakarta.annotation.Nonnull Object expression) {
    
    this.expression = expression;
    return this;
  }

  /**
   * 
   * @return expression
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXPRESSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getExpression() {
    return expression;
  }


  @JsonProperty(JSON_PROPERTY_EXPRESSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpression(@jakarta.annotation.Nonnull Object expression) {
    this.expression = expression;
  }

  public QueryRequest metadata(@jakarta.annotation.Nonnull List<String> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public QueryRequest addMetadataItem(String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new ArrayList<>();
    }
    this.metadata.add(metadataItem);
    return this;
  }

  /**
   * 
   * @return metadata
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMetadata(@jakarta.annotation.Nonnull List<String> metadata) {
    this.metadata = metadata;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryRequest queryRequest = (QueryRequest) o;
    return Objects.equals(this.entities, queryRequest.entities) &&
        Objects.equals(this.attrs, queryRequest.attrs) &&
        Objects.equals(this.expression, queryRequest.expression) &&
        Objects.equals(this.metadata, queryRequest.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entities, attrs, expression, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryRequest {\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("    attrs: ").append(toIndentedString(attrs)).append("\n");
    sb.append("    expression: ").append(toIndentedString(expression)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

