/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package city.makeour.ngsi.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RetrieveEntityTypeResponse
 */
@JsonPropertyOrder({
  RetrieveEntityTypeResponse.JSON_PROPERTY_ATTRS,
  RetrieveEntityTypeResponse.JSON_PROPERTY_COUNT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-27T19:56:40.594359+09:00[Asia/Tokyo]", comments = "Generator version: 7.12.0")
public class RetrieveEntityTypeResponse {
  public static final String JSON_PROPERTY_ATTRS = "attrs";
  @jakarta.annotation.Nonnull
  private Object attrs;

  public static final String JSON_PROPERTY_COUNT = "count";
  @jakarta.annotation.Nonnull
  private Integer count;

  public RetrieveEntityTypeResponse() {
  }

  public RetrieveEntityTypeResponse attrs(@jakarta.annotation.Nonnull Object attrs) {
    
    this.attrs = attrs;
    return this;
  }

  /**
   * 
   * @return attrs
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ATTRS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getAttrs() {
    return attrs;
  }


  @JsonProperty(JSON_PROPERTY_ATTRS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAttrs(@jakarta.annotation.Nonnull Object attrs) {
    this.attrs = attrs;
  }

  public RetrieveEntityTypeResponse count(@jakarta.annotation.Nonnull Integer count) {
    
    this.count = count;
    return this;
  }

  /**
   * 
   * @return count
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCount() {
    return count;
  }


  @JsonProperty(JSON_PROPERTY_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCount(@jakarta.annotation.Nonnull Integer count) {
    this.count = count;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetrieveEntityTypeResponse retrieveEntityTypeResponse = (RetrieveEntityTypeResponse) o;
    return Objects.equals(this.attrs, retrieveEntityTypeResponse.attrs) &&
        Objects.equals(this.count, retrieveEntityTypeResponse.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attrs, count);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetrieveEntityTypeResponse {\n");
    sb.append("    attrs: ").append(toIndentedString(attrs)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

