/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package city.makeour.ngsi.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RetrieveRegistrationResponse
 */
@JsonPropertyOrder({
  RetrieveRegistrationResponse.JSON_PROPERTY_ID,
  RetrieveRegistrationResponse.JSON_PROPERTY_DESCRIPTION,
  RetrieveRegistrationResponse.JSON_PROPERTY_DATA_PROVIDED,
  RetrieveRegistrationResponse.JSON_PROPERTY_PROVIDER,
  RetrieveRegistrationResponse.JSON_PROPERTY_EXPIRES,
  RetrieveRegistrationResponse.JSON_PROPERTY_STATUS,
  RetrieveRegistrationResponse.JSON_PROPERTY_FORWARDING_INFORMATION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-27T19:56:40.594359+09:00[Asia/Tokyo]", comments = "Generator version: 7.12.0")
public class RetrieveRegistrationResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nonnull
  private String description;

  public static final String JSON_PROPERTY_DATA_PROVIDED = "dataProvided";
  @jakarta.annotation.Nonnull
  private Object dataProvided;

  public static final String JSON_PROPERTY_PROVIDER = "provider";
  @jakarta.annotation.Nonnull
  private Object provider;

  public static final String JSON_PROPERTY_EXPIRES = "expires";
  @jakarta.annotation.Nonnull
  private String expires;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private String status;

  public static final String JSON_PROPERTY_FORWARDING_INFORMATION = "forwardingInformation";
  @jakarta.annotation.Nonnull
  private Object forwardingInformation;

  public RetrieveRegistrationResponse() {
  }

  public RetrieveRegistrationResponse id(@jakarta.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * 
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public RetrieveRegistrationResponse description(@jakarta.annotation.Nonnull String description) {
    
    this.description = description;
    return this;
  }

  /**
   * 
   * @return description
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(@jakarta.annotation.Nonnull String description) {
    this.description = description;
  }

  public RetrieveRegistrationResponse dataProvided(@jakarta.annotation.Nonnull Object dataProvided) {
    
    this.dataProvided = dataProvided;
    return this;
  }

  /**
   * 
   * @return dataProvided
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DATA_PROVIDED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getDataProvided() {
    return dataProvided;
  }


  @JsonProperty(JSON_PROPERTY_DATA_PROVIDED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDataProvided(@jakarta.annotation.Nonnull Object dataProvided) {
    this.dataProvided = dataProvided;
  }

  public RetrieveRegistrationResponse provider(@jakarta.annotation.Nonnull Object provider) {
    
    this.provider = provider;
    return this;
  }

  /**
   * 
   * @return provider
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getProvider() {
    return provider;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProvider(@jakarta.annotation.Nonnull Object provider) {
    this.provider = provider;
  }

  public RetrieveRegistrationResponse expires(@jakarta.annotation.Nonnull String expires) {
    
    this.expires = expires;
    return this;
  }

  /**
   * 
   * @return expires
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXPIRES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExpires() {
    return expires;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpires(@jakarta.annotation.Nonnull String expires) {
    this.expires = expires;
  }

  public RetrieveRegistrationResponse status(@jakarta.annotation.Nonnull String status) {
    
    this.status = status;
    return this;
  }

  /**
   * 
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull String status) {
    this.status = status;
  }

  public RetrieveRegistrationResponse forwardingInformation(@jakarta.annotation.Nonnull Object forwardingInformation) {
    
    this.forwardingInformation = forwardingInformation;
    return this;
  }

  /**
   * 
   * @return forwardingInformation
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FORWARDING_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getForwardingInformation() {
    return forwardingInformation;
  }


  @JsonProperty(JSON_PROPERTY_FORWARDING_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setForwardingInformation(@jakarta.annotation.Nonnull Object forwardingInformation) {
    this.forwardingInformation = forwardingInformation;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetrieveRegistrationResponse retrieveRegistrationResponse = (RetrieveRegistrationResponse) o;
    return Objects.equals(this.id, retrieveRegistrationResponse.id) &&
        Objects.equals(this.description, retrieveRegistrationResponse.description) &&
        Objects.equals(this.dataProvided, retrieveRegistrationResponse.dataProvided) &&
        Objects.equals(this.provider, retrieveRegistrationResponse.provider) &&
        Objects.equals(this.expires, retrieveRegistrationResponse.expires) &&
        Objects.equals(this.status, retrieveRegistrationResponse.status) &&
        Objects.equals(this.forwardingInformation, retrieveRegistrationResponse.forwardingInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, description, dataProvided, provider, expires, status, forwardingInformation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetrieveRegistrationResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    dataProvided: ").append(toIndentedString(dataProvided)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    expires: ").append(toIndentedString(expires)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    forwardingInformation: ").append(toIndentedString(forwardingInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

