/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package city.makeour.ngsi.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RetrieveEntityAttributesResponse
 */
@JsonPropertyOrder({
  RetrieveEntityAttributesResponse.JSON_PROPERTY_TEMPERATURE,
  RetrieveEntityAttributesResponse.JSON_PROPERTY_HUMIDITY,
  RetrieveEntityAttributesResponse.JSON_PROPERTY_LOCATION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-27T19:56:40.594359+09:00[Asia/Tokyo]", comments = "Generator version: 7.12.0")
public class RetrieveEntityAttributesResponse {
  public static final String JSON_PROPERTY_TEMPERATURE = "temperature";
  @jakarta.annotation.Nonnull
  private Object temperature;

  public static final String JSON_PROPERTY_HUMIDITY = "humidity";
  @jakarta.annotation.Nonnull
  private Object humidity;

  public static final String JSON_PROPERTY_LOCATION = "location";
  @jakarta.annotation.Nonnull
  private Object location;

  public RetrieveEntityAttributesResponse() {
  }

  public RetrieveEntityAttributesResponse temperature(@jakarta.annotation.Nonnull Object temperature) {
    
    this.temperature = temperature;
    return this;
  }

  /**
   * 
   * @return temperature
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TEMPERATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getTemperature() {
    return temperature;
  }


  @JsonProperty(JSON_PROPERTY_TEMPERATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTemperature(@jakarta.annotation.Nonnull Object temperature) {
    this.temperature = temperature;
  }

  public RetrieveEntityAttributesResponse humidity(@jakarta.annotation.Nonnull Object humidity) {
    
    this.humidity = humidity;
    return this;
  }

  /**
   * 
   * @return humidity
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HUMIDITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getHumidity() {
    return humidity;
  }


  @JsonProperty(JSON_PROPERTY_HUMIDITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHumidity(@jakarta.annotation.Nonnull Object humidity) {
    this.humidity = humidity;
  }

  public RetrieveEntityAttributesResponse location(@jakarta.annotation.Nonnull Object location) {
    
    this.location = location;
    return this;
  }

  /**
   * 
   * @return location
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getLocation() {
    return location;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocation(@jakarta.annotation.Nonnull Object location) {
    this.location = location;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetrieveEntityAttributesResponse retrieveEntityAttributesResponse = (RetrieveEntityAttributesResponse) o;
    return Objects.equals(this.temperature, retrieveEntityAttributesResponse.temperature) &&
        Objects.equals(this.humidity, retrieveEntityAttributesResponse.humidity) &&
        Objects.equals(this.location, retrieveEntityAttributesResponse.location);
  }

  @Override
  public int hashCode() {
    return Objects.hash(temperature, humidity, location);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetrieveEntityAttributesResponse {\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    humidity: ").append(toIndentedString(humidity)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

