/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package city.makeour.ngsi.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpdateOrAppendEntityAttributesRequest
 */
@JsonPropertyOrder({
  UpdateOrAppendEntityAttributesRequest.JSON_PROPERTY_AMBIENT_NOISE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-27T19:56:40.594359+09:00[Asia/Tokyo]", comments = "Generator version: 7.12.0")
public class UpdateOrAppendEntityAttributesRequest {
  public static final String JSON_PROPERTY_AMBIENT_NOISE = "ambientNoise";
  @jakarta.annotation.Nonnull
  private Object ambientNoise;

  public UpdateOrAppendEntityAttributesRequest() {
  }

  public UpdateOrAppendEntityAttributesRequest ambientNoise(@jakarta.annotation.Nonnull Object ambientNoise) {
    
    this.ambientNoise = ambientNoise;
    return this;
  }

  /**
   * 
   * @return ambientNoise
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMBIENT_NOISE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getAmbientNoise() {
    return ambientNoise;
  }


  @JsonProperty(JSON_PROPERTY_AMBIENT_NOISE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmbientNoise(@jakarta.annotation.Nonnull Object ambientNoise) {
    this.ambientNoise = ambientNoise;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateOrAppendEntityAttributesRequest updateOrAppendEntityAttributesRequest = (UpdateOrAppendEntityAttributesRequest) o;
    return Objects.equals(this.ambientNoise, updateOrAppendEntityAttributesRequest.ambientNoise);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ambientNoise);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateOrAppendEntityAttributesRequest {\n");
    sb.append("    ambientNoise: ").append(toIndentedString(ambientNoise)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

